### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by C0ntroller** [Praktikum-PvAS/process-historian#27]

**Comment by C0ntroller** [comment]
Things to be added:
- [ ] When using `docker run` you have to be in the root folder of the project (otherwise `$(pwd)/config` will not be the correct config folder.
- [ ] How to run the tests
- [ ] Licencing

**Comment by OParczyk** [comment]
Licensing added via 2d4e854644541af350a78c364f103624b39e76a4
